language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-18mode
  - rbx-19mode
# descomentar la siguiente línea en caso de que tu proyecto necesite algo mas que  `rake`:
# script: bundle exec rspec spec